apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-deployments-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: argo-workflows
roleRef:
  kind: ClusterRole
  name: argo-deployments-clusterrole
  apiGroup: rbac.authorization.k8s.io
