apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: docker-event-source
  namespace: argo-events
spec:
  docker:
    example:
      endpoint: "unix:///var/run/docker.sock"
      events:
        - push
