apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: docker-events
spec:
  docker:
    - name: "docker-image-push"
      registry: "your-docker-registry"
      event:
        repository: "your-repository-name"
        tag: "latest"
