apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: slack-events
  namespace: argo-events
spec:
  slack:
    example-slack-trigger:   # Ensure this name is correctly defined and matches the Sensor configuration
      token:
        valueFrom:
          secretKeyRef:
            name: slack-token
            key: eG94Yi0zMjA0MDQ4MzAxOTExLTMyMTIwNDc2NDA3OTAtdFVmRnF0a2d3WFQxd25xM2h6VnFNTHo3
      channels:
        - "ISD-Notification"
