apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: slack-events
  namespace: argo-events
spec:
  slack:
    example-slack-trigger:
      token:
        valueFrom:
          secretKeyRef:
            name: slack-token
            key: slack-token-key
      channels:
        - "ISD-Notification"
