apiVersion: v1
kind: Service
metadata:
  name: webhook-event-source
  namespace: argo-events
spec:
  type: NodePort
  ports:
  - port: 12000
    targetPort: 12000
    nodePort: 32000
  selector:
    app: webhook-event-source
