# Submit with: argo submit artifact-passing.yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  generateName: artifact-passing-
  namespace: test
spec:
  entrypoint: artifact-demo
  templates:
  - name: artifact-demo
    script:
      image: alpine:3.6
      command: [sh, -c]
      source: |
        echo "hello world" > /tmp/hello.txt
      outputs:
        artifacts:
        - name: hello-art
          path: /tmp/hello.txt
  - name: artifact-consume
    inputs:
      artifacts:
      - name: hello-art
        path: /tmp/hello.txt
    container:
      image: alpine:3.6
      command: [cat]
      args: ["/tmp/hello.txt"]
