apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ci-pipeline-python-app-wf
  namespace: test
spec:
  entrypoint: ci-pipeline-python-app-wf
  volumes:
    - name: test-vol
      hostPath:
        path: /path/to/tests
  templates:
  - name: python-app
    steps:
    - - name: build
        template: build
      - name: test
        template: test
      - name: deploy
        template: deploy
  - name: build
    container:
      image: python:3.11
      command: [python]
      args: ["-c", "print('build')"]
  - name: test
    container:
      image: python:3.11
      command: [python]
      args: ["-m","unittest","discover","-s","/app/tests"]
      volumeMounts:
        - name: test-vol
          mountPath: /app/tests
  - name: deploy
    container:
      image: python:3.11
      command: [python]
      args: ["-c", "print('deploy')"]
