apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: argo-wf-gag-template # Name of this Workflow
  namespace: test
spec:
  entrypoint: dag-template # Defines "dag-template" as the "main" template
  templates:
  - name: dag-template # Defining the "dag template" as a Template Invocator
    dag:
      tasks:
      - name: A
        template: container-template
      - name: B
        template: script-template
        dependencies: [A]
      - name: C
        template: resource-template
        dependencies: [A]
      - name: D
        template: delay-template
        dependencies: [B, C]

  - name: container-template # Defining the "container template" as a Template Definition
    container:
      image: alpine
      command: ["/bin/sh", "-c"]
      args: ["echo Hello from container template"]

  - name: script-template # Defining the "script template" as a Template Definition
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        i = random.randint(1, 100)
        print(i)

  - name: resource-template # Defining the "resource template" as a Template Definition
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          generateName: argo-wf-resource-template-cm-
        data:
          created_by: argo-workflows

  - name: delay-template # Defining the "delay template" as a Template Definition
    suspend:
      duration: "20s"
