apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  generateName: k8s-jobs-
  namespace: test
spec:
  entrypoint: pi-tmpl
  templates:
  - name: pi-tmpl
    resource:
      action: create
      successCondition: status.succeeded > 0
      failureCondition: status.failed > 3
      manifest: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          generateName: pi-job-
        spec:
          template:
            spec:
              containers:
              - name: pi
                image: perl
                command: ["perl","-Mbignum=bpi","-wle","print bpi(2000)"]
              restartPolicy: Never
          backoffLimit: 4
    outputs:
      parameters:
      - name: job-name
        valueFrom:
          jsonPath: '{.metadata.name}'
      - name: job-obj
        valueFrom:
          jqFilter: '.'
