# error: The WorkflowTemplate "k8s-jobs-" is invalid: metadata.name: Invalid value: "k8s-jobs-": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')


apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: kubernets-jobs-
  namespace: test
spec:
  entrypoint: pi-tmpl
  templates:
  - name: pi-tmpl
    resource:
      action: create
      successCondition: status.succeeded > 0
      failureCondition: status.failed > 3
      manifest: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          generateName: pi-job-
        spec:
          template:
            spec:
              containers:
              - name: pi
                image: perl
                command: ["perl","-Mbignum=bpi","-wle","print bpi(2000)"]
              restartPolicy: Never
          backoffLimit: 4
    outputs:
      parameters:
      - name: job-name
        valueFrom:
          jsonPath: '{.metadata.name}'
      - name: job-obj
        valueFrom:
          jqFilter: '.'




