apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  generateName: hello-param-
  namespace: test
spec:
  entrypoint: whalesay
  arguments:
    parameters:
    - name: message
      value: "hello world"
  templates:
  - name: whalesay
    inputs:
      parameters: [{name: message}]
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
