apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: basic-spinnaker-pipeline
spec:
  entrypoint: pipeline
  templates:
  - name: pipeline
    steps:
    - - name: build
        template: build
    - - name: test
        template: test
    - - name: deploy
        template: deploy

  - name: build
    container:
      image: nginx:latest 
      command: [sh, -c]
      args: ["echo 'Building applications...' && sleep 10"]

  - name: test
    container:
      image: nginx:latest 
      command: [sh, -c]
      args: ["echo 'Running test...' && sleep 10"]

  - name: deploy
    container:
      image: nginx:latest 
      command: [sh, -c]
      args: ["echo 'Deploying application...' && sleep 10"]
