apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: argo-wf  # Name of this Workflow
  namespace: test
spec:
  entrypoint: steps-template # Defines "steps-template" as the "main" template
  templates:
  - name: steps-template # Defining the "steps template" as a Template Invocator
    steps:
    - - name: step1
        template: container-template
    - - name: step2a
        template: script-template
      - name: step2b
        template: resource-template
    - - name: step3
        template: delay-template

  - name: container-template # Defining the "container template" as a Template Definition
    container:
      image: alpine
      command: ["/bin/sh", "-c"]
      args: ["echo Hello from container template"]

  - name: script-template # Defining the "script template" as a Template Definition
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        i = random.randint(1, 100)
        print(i)

  - name: resource-template # Defining the "resource template" as a Template Definition
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          generateName: argo-wf-resource-template-cm-
        data:
          created_by: argo-workflows

  - name: delay-template # Defining the "delay template" as a Template Definition
    suspend:
      duration: "20s"
