apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-apps
spec:
  project: default
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/NaveenBalagouni/argo-workflows.git
    targetRevision: HEAD
    path: Workflow-Template/nginx-sample
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  hooks:
    sync:
      postSync:
        - exec:
            command:
              - /bin/sh
              - -c
              - >
                curl -X POST https://argo.srini-striks.opsmx.co/webhook -H "Content-Type: application/json" -d '{"trigger": "argocd-sync"}'
