apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: docker-sensor
  namespace: argo
spec:
  triggers:
    - template:
        name: docker-trigger
        http:
          url: "http://localhost:8080"  # URL for the webhook to trigger the workflow
          method: POST
  eventSourceRef:
    name: docker-event-source  # Reference to the event source
