apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: slack-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: workflow-completed
      eventSourceName: slack-events
      eventName: example-slack-trigger
  triggers:
    - template:
        name: slack-notification
        slack:
          token:
            valueFrom:
              secretKeyRef:
                name: slack-token
                key: slack-token-key
          channel: "#ISD-Notification"
          message: "Workflow {{workflow.name}} has completed with status {{workflow.status}}."
