apiVersion: v1
kind: Secret
metadata:
  name: slack-token
  namespace: argo-events
type: Opaque
data:
  slack-token-key: eG94Yi0zMjA0MDQ4MzAxOTExLTMyMTIwNDc2NDA3OTAtdFVmRnF0a2d3WFQxd25xM2h6VnFNTHo3  # Example encoded token
