apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: nginx-world
spec:
  entrypoint: sample-nginx-world  # Corrected to match the template name
  templates:
<<<<<<< HEAD
    - name: sample-nginx-world
      container:
        image: nginx:latest
        command:
          - sh
          - -c
        args:
          - echo Hello, World!
=======
  - name: hello-world
    container:
      image: nginx:latest
      command: [sh, -c]
      args: ["echo Hello, World!"]
>>>>>>> 6cc53b1a2d550c78d4af7bb23aa24aa17931f3b7
