apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: nginx-world
spec:
  entrypoint: sample-nginx-world  # Corrected to match the template name
  templates:
    - name: sample-nginx-world
      container:
        image: nginx:latest
        command:
          - sh
          - -c
        args:
          - echo Hello, World!
