apiVersion: apps/v1
kind: Application
metadata:
  name: deploy-pipeline-app
spec:
  source:
    repoURL: https://github.com/NaveenBalagouni/argo-workflows.git
    path: issuer-app
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: naveen
