apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: isd-argo-install
  namespace: argocd
spec:
  destination:
    namespace: isd-argo
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/NaveenBalagouni/argo-workflows.git'
    path: isd-helm-resource
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
