apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-pipeline
  namespace: argo-workflows
spec:
  entrypoint: deploy-pipeline
  serviceAccountName: argo-workflows-sa
  templates:
    - name: deploy-pipeline
      steps:
        - - name: clone-repo
            template: clone-repo

          - name: maven-build
            template: maven-build
          
          - name: kaniko-build-push
            template: kaniko-build-push

          - name: update-values-yaml
            template: update-values-yaml

    - name: clone-repo
      container:
        image: "quay.io/opsmxpublic/opsmx-custom-binaries:kubectl-spin-cli-git-bash-jq-yq-argocd-v2"
        command: ["/bin/bash", "-c"]
        args:
          - |
            echo "Cloning repository and checking out branch..."
            git_url=$(echo $GIT_URL)
            git_branch=$(echo $GIT_BRANCH)
            git_username=$(echo $GIT_USERNAME)
            git_credentials=$(echo $GIT_TOKEN)
            
            echo "Git URL: ${git_url}"
            echo "Git Branch: ${git_branch}"
            echo "Git Username: ${git_username}"
            git config --global credential.helper store
            echo "https://${git_username}:${git_credentials}@${git_url}" > /mnt/git-repo/.git-credentials
            git clone -b ${git_branch} ${git_url} /mnt/git-repo
            cd /mnt/git-repo
            git checkout ${git_branch}
        env:
          - name: GIT_URL
            valueFrom:
              secretKeyRef:
                name: git-credentials
                key: git-url
          - name: GIT_BRANCH
            value: "main"
          - name: GIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: git-credentials
                key: git-username
          - name: GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: git-credentials
                key: gittoken

    - name: maven-build
      container:
        image: "maven"
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Building project with Maven..."
            echo "Cloning repository and checking out branch..."
            git_url=$(echo $GIT_URL)
            git_branch=$(echo $GIT_BRANCH)
            git_username=$(echo $GIT_USERNAME)
            git_credentials=$(echo $GIT_TOKEN)
            
            echo "Git URL: ${git_url}"
            echo "Git Branch: ${git_branch}"
            echo "Git Username: ${git_username}"
            echo "Git Token: ${git_credentials}"
            
            git clone -b ${git_branch} ${git_url} /mnt/git-repo
            cd /mnt/git-repo
            ls -ltra /mnt/git-repo/
            
            mvn -B -DskipTests clean install -e

        env:
          - name: GIT_URL
            valueFrom:
              secretKeyRef:
                name: git-credentials
                key: git-url
          - name: GIT_BRANCH
            value: "main"
          - name: GIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: git-credentials
                key: git-username
          - name: GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: git-credentials
                key: gittoken

    - name: kaniko-build-push
      inputs:
        parameters:
          - name: docker-registry
            value: quay.io
          - name: docker-image
            value: opsmxpublic/baseline-issuegen
          - name: image-tag
            value: latest
      container:
        image: gcr.io/kaniko-project/executor:v1.9.0-debug
        imagePullPolicy: Always
        command: ["/kaniko/executor"]
        args:
          [
            "--context=git://github.com/NaveenBalagouni/kaniko-build.git",
            "--dockerfile=/mnt/git-repo/Dockerfile",
            "--destination={{inputs.parameters.docker-registry}}/{{inputs.parameters.docker-image}}:{{inputs.parameters.image-tag}}"
          ]
        volumeMounts:
          - name: docker-config-volume
            mountPath: /kaniko/.docker/
      volumes:
        - name: docker-config-volume
          secret:
            secretName: docker-credentialsquay
            items:
              - key: .dockerconfigjson
                path: config.json

    - name: update-values-yaml
      container:
        image: "quay.io/opsmxpublic/opsmx-custom-binaries:kubectl-spin-cli-git-bash-jq-yq-argocd-v2"
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Cloning Git repository..."
            git_url=$(echo $GIT_URL)
            git_branch=$(echo $GIT_BRANCH)
            git_username=$(echo $GIT_USERNAME)
            git_credentials=$(echo $GIT_TOKEN)
            
            echo "Git URL: ${git_url}"
            echo "Git Branch: ${git_branch}"
            echo "Git Username: ${git_username}"
            
            git clone ${git_url} /mnt/git-repo
            echo "Current directory: $(pwd)"
            ls -ltra /mnt/git-repo/
    
        

            image=$(cat /mnt/git-repo/)
            echo "Image tag: $image"

          
            yq eval ".image = \"$image\"" -i /mnt/git-repo/values.yaml
           

            echo "Pushing changes to GitHub..."
            git push git://$GIT_USERNAME:$GIT_TOKEN@${git_url} $GIT_BRANCH
        env:
          - name: GIT_URL
            valueFrom:
              secretKeyRef:
                name: git-credentials
                key: git-url
          - name: GIT_BRANCH
            value: "main"
          - name: GIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: git-credentials
                key: git-username
          - name: GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: git-credentials
                key: gittoken
