apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
  namespace: nginx-argo  # Set the namespace to nginx-argo
data:
  nginx.conf: |
    events {}

    http {
        server {
            listen 80;

            location /webhook {
                proxy_pass http://argo-workflow-service:8080;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
